### ISSUE TITLE
Weather API testing and implementation

### ISSUE THREAD

**Issue by SysAdminSfC** [ScienceForChange/odourCollect_2.0#203] opened 2024-02-15 10:03 UTC

**Comment by CarlosMillanSfC** [comment] 2024-02-20 17:42
no me repitas issues

**Comment by CarlosMillanSfC** [comment] 2024-02-20 17:43
duplicated #228

**Comment by CarlosMillanSfC** [comment] 2024-02-20 17:44
Duplicate of #228

**Comment by CarlosMillanSfC** [comment] 2024-02-20 17:45
Duplicate of #228

**Closed by CarlosMillanSfC** 2024-02-20 17:45 UTC
